general {
    lock_cmd = pidof hyprlock || hyprlock       # avoids starting multiple instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after sleep
}

listener {
    timeout = 2400                                # 40 minutes
    on-timeout = systemctl poweroff               # shutdown command
}
